services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: libbook

  backend:
    image: patcharapon07/libbook-api:v1.0.0
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: libbook
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    image: patcharapon07/libbook-web:v1.0.0
    ports:
      - "${FRONTEND_PORT:-8080}:80"